TARGET    = doctored-sag1021I-ivi
LIBRARIES = fx2 fx2usb fx2isrs
MODEL     = small
SOURCES   = main FX2LPSerial

#LIBFX2  = ../../../libfx2/firmware/library
LIBFX2  = ../../../../libfx2/firmware/library
#LIBFX2  = ..\..\..\..\libfx2\firmware\library
include $(LIBFX2)/fx2rules.mk
